### ISSUE TITLE
Code coverage workflow

### ISSUE THREAD

**Issue by kralka** [google/scaaml#192]
Add a code coverage workflow (how well the code is unittested, new code comes with code coverage...)

**Comment by kralka** [comment]
@LucaTomasko what do you think about the following? https://coverage.readthedocs.io/en/7.4.0/ combined with https://github.com/google/scaaml/blob/main/.github/workflows/pytest.yml

**Comment by jmichelp** [comment]
As mentioned in #221 a problem matcher won't really work in this scenario.

Workflow is in place and running. Should we close this issue?
