### ISSUE TITLE
Python venv not compatible with key_recovery_demo.ipynb

### ISSUE THREAD

**Issue by mattiamirigaldi** [google/scaaml#307]
Trying to load the model in cell 6 of **key_recovery_demo.ipnb** gives error 

**Code :**
```
# let's select an attack point that have all the needed models -- Key is not a good target: it doesn't work
ATTACK_POINT = 'sub_bytes_out'

# let's also pick the key byte we want to use SCAAML to recover and load the related model
ATTACK_BYTE = 7

# load model
model = load_model_from_disk(available_models[ATTACK_POINT][ATTACK_BYTE])
```

**Error**
```
ValueError: File format not supported: filepath=models/stm32f415-tinyaes-cnn-v10-ap_sub_bytes_out-byte_7-len_20000. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. 
```

The venv used is the one generated by **requirements.txt**

**Comment by mattiamirigaldi** [comment]
I solved it by downgrading my python version to 3.9 and using the tensorflow version 2.10 (and others by hand fix).

But I really think the notebook should be upgraded to be compatible with the venv build with the requirement file.

**Comment by tanvir-jewel** [comment]
@mattiamirigaldi , what the other hand fixes have you used? 

Can you please share your fixed notebook or the process?

**Comment by kralka** [comment]
@tanvir-jewel https://github.com/google/scaaml/tree/main/scaaml_intro is code for the presentation from DEFCON 27 (year 2019). That code does not support Keras3. So you probably need old Python and old TensorFlow.

If you want to experiment with the GPAM paper: https://github.com/google/scaaml/tree/main/papers/2024/GPAM (even that needs a little bit older version of TensorFlow).

I am a bit cautious to update the code as 1) archiving 2) compatibility with pretrained and saved models. I will think of a solution (providing separate `requirements.txt` or a docker container to run archived version and / or updating the code to newer libraries). https://github.com/google/scaaml/issues/342
